Repository AY2425S1-CS2113-W14-1/tp, pull requests merged in 2024-10, with the labels that each got.

#26 Add delete command
  src/main/java/seedu/commands/DeleteCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#60 Further categorise income and spendings
  src/main/java/seedu/classes/Ui.java
  src/main/java/seedu/commands/ListCommand.java
Labels: type.Story, priority.High

#62 Branch UG for updated user guide
  docs/UserGuide.md
  src/main/java/seedu/classes/Ui.java
Labels: type.Task, priority.Medium

#70 Update developer and user guide
  docs/DeveloperGuide.md
  docs/Diagrams/storage.drawio
  docs/Diagrams/storageLoad.png
  docs/Diagrams/storageSave.png
  docs/UserGuide.md
  src/main/java/seedu/wiagi/Wiagi.java
Labels: priority.Medium
