Repository AY2425S1-CS2113-W14-1/tp, pull requests merged in 2024-11, with the labels that each got.

#174 Branch storage load check for when it is corrupted
  logger.log.1
  logger.log.2
  src/main/java/seedu/classes/Constants.java
  src/main/java/seedu/classes/Ui.java
  src/main/java/seedu/exception/WiagiStorageCorruptedException.java
  src/main/java/seedu/storage/IncomeListStorage.java
  src/main/java/seedu/storage/LoadStorageCheck.java
  src/main/java/seedu/storage/SpendingListStorage.java
  src/main/java/seedu/type/EntryType.java
  src/test/java/seedu/storage/IncomeListStorageTest.java
  src/test/java/seedu/storage/SpendingListStorageTest.java
Labels: severity.Medium

#176 Fix bug for double overflow and not enclosed attribute
  artifacts/tp_jar/tp.jar
  docs/UserGuide.md
  src/main/java/seedu/classes/Constants.java
  src/main/java/seedu/classes/Ui.java
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/CommandUtils.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/recurrence/Recurrence.java
  src/main/java/seedu/type/EntryType.java
  src/main/java/seedu/type/IncomeList.java
  src/main/java/seedu/type/SpendingList.java
  src/main/java/seedu/wiagi/Wiagi.java
  src/test/java/seedu/commands/AddCommandTest.java
  src/test/java/seedu/commands/DeleteCommandTest.java
  src/test/java/seedu/commands/EditCommandTest.java
Labels: type.Bug, priority.Medium

#233 Test for IncomeListStorage and LoadStorageCheck
  src/main/java/seedu/storage/LoadStorageCheck.java
  src/test/java/seedu/storage/IncomeListStorageTest.java
  src/test/java/seedu/storage/LoadStorageCheckTest.java
  src/test/java/seedu/storage/LoginStorageTest.java
Labels: type.Task, priority.Medium, severity.Low

#253 Change logic of exceptions for budget
  src/main/java/seedu/commands/BudgetCommand.java
Labels: type.Bug

#258 Overspend message for edit
  src/main/java/seedu/commands/EditCommand.java
  src/main/java/seedu/storage/LoginStorage.java
Labels: type.Bug
